### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by ratawar**
- used 'clean code' VS function across the entire solution, and some cleanups
- fixed typography errors
- improved the preprocessor directives regex for syntax highlighting
- now 'go to definition' shortcut (ctrl+click on a word) and the definition window (ctrl+shift+f) shoudn't crash when attempting to access defintions that are located in scripting directories defined after the first one in settings

### CODE REVIEW

**Comment by Hexer10** [comment]
Just a side note: The build fails since the `setup-msbuild` action needs to be updated, on the `master` branch this is already done

**Comment by ratawar** [comment]
todo: go to definition must work with methods

**Comment by ratawar** [comment]
(by pressing Enter in a selected symbol in the definition window)
also added a return in the same function to avoid multiple openings, same intended effect from one of the past commits

**Comment by ratawar** [comment]
there is still some fuzziness to be worked on

https://user-images.githubusercontent.com/20617661/105648057-2b4d9500-5e88-11eb-960e-226469eff2e4.mp4

**Comment by ratawar** [comment]
This last commit makes SPCode forced to open with administrator permissions. Currently searching for alternatives, as I look forward to avoiding users having to deal with the UAC Windows prompt.

**Comment by ratawar** [comment]
Now that I managed to send all configurations to %appdata% and make the program locate everything it needs to read/write there, it's possible to install SPCode anywhere without issue.
We need to review the portable version build to make sure the IDE continues locating its files properly.

**Comment by ratawar** [comment]
As a side note, these implementations are only being geared towards the correct functioning of the standalone version, and at the same time for ground preparation when it comes the time to adapt the code to compile and compress the portable version.

**Comment by ratawar** [comment]
I believe this is ready for release/testing. Full changelog is:
- Code cleanup
- Some typography errors corrected
- Changed preprocessor directives RegEx for highlighting to match all words that begin with a hash #
- Fixed ctrl+clicking on symbols (partially including methodmap and enum structs symbols) not working for all defined scripting directories
- Fixed the Definition Window (ctrl+shift+f) not working/crashing for all defined scripting directories
- You can press Enter now to go to a definition in the Definition Window
- Fixed IDE crashing when attempting to reformat all editors with none opened
- Refactored installation to send all configuration and setting files, templates and temporary files to ``%appdata%``, even if the program gets installed anywhere else.
- Implemented an IsLocalInstallation detection for compatibility with the portable version - program knows where to fetch the contents of the ``sourcepawn`` folder (configuration and setting files, templates and temporary files)

**Comment by Hexer10** [comment]
Thanks for all the work, I'm merging this, I'll just test a bit before pushing the release (and run the code reformatter, tell me if you think the styling should be changed in your opinion).

**Pull request merged**
